In [136]:
from pgmpy.models import BayesianNetwork
from pgmpy.factors.discrete import TabularCPD
m1 = BayesianNetwork()
m1.add_nodes_from(['X','Y','Z'])
m1.get_independencies()
cpd_X = TabularCPD(variable="X", variable_card=2, values=[[0.4], [0.6]])
cpd_Y = TabularCPD(variable="Y", variable_card=2, values=[[0.7], [0.3]])
cpd_Z = TabularCPD(variable="Z", variable_card=2, values=[[0.1], [0.9]])
m1.add_cpds(cpd_X,cpd_Y,cpd_Z)

In [29]:
import numpy as np
from pgmpy.factors.discrete import JointProbabilityDistribution
p1 = [0.4, 0.6]
p2 = [0.7, 0.3]
p3 = [0.1, 0.9]
jp = []
for i in p1:
    for j in p2:
        for k in p3:
            jp.append(i*j*k)        
print(jp)
JPD = JointProbabilityDistribution(["X",'Y','Z'],[2,2,2], jp)
m1.is_imap(JPD)

[0.027999999999999997, 0.252, 0.012, 0.108, 0.042, 0.378, 0.018, 0.162]


True

In [53]:
m2 = BayesianNetwork()
m2.add_nodes_from(['X','Y','Z'])
m2.add_edge('Y','X')
m2.add_edge('Y','Z')
cpd_Y = TabularCPD(variable="Y", variable_card=2, values=[[0.7], [0.3]])
cpd_X = TabularCPD(
        variable="X",
        variable_card=2,
        values=[
            [0.4, 0.2],
            [0.6, 0.8],
        ],
        evidence=["Y"],
        evidence_card=[2],
    )
cpd_Z = TabularCPD(
        variable="Z",
        variable_card=2,
        values=[
            [0.5, 0.4],
            [0.5, 0.6],
        ],
        evidence=["Y"],
        evidence_card=[2],
    )
print(cpd_X.is_valid_cpd(),cpd_Y.is_valid_cpd(),cpd_Z.is_valid_cpd())
m2.add_cpds(cpd_X,cpd_Y,cpd_Z)
m2.get_independencies()

True True True


(Z ⟂ X | Y)
(X ⟂ Z | Y)

In [31]:
from pgmpy.base import DAG
G = DAG()
G.add_nodes_from(m2.nodes)
G.add_edges_from(m2.edges)

In [32]:
print(G.get_independencies())

(Z ⟂ X | Y)
(X ⟂ Z | Y)


In [60]:
import numpy as np
P_Y = np.array([[0.7], [0.3]])
P_X_Y = np.array([
            [0.4, 0.2],
            [0.6, 0.8],
        ])
P_Z_Y = np.array([
            [0.5, 0.4],
            [0.5, 0.6],
        ])
jpd = []
for Y in [0,1]:
    for X in [0,1]:
        for Z in [0,1]:
            p_yxz =  np.multiply(
                np.multiply(P_Y[Y], P_X_Y[X,Y]),
                P_Z_Y[Z,Y])
            jpd.append(p_yxz[0])
            print(Y,X,Z, p_yxz)
print(jpd)
print(sum(jpd))
prob = JointProbabilityDistribution(["Y",'X','Z'],[2,2,2], jpd)
print(m2.is_imap(prob))

0 0 0 [0.14]
0 0 1 [0.14]
0 1 0 [0.21]
0 1 1 [0.21]
1 0 0 [0.024]
1 0 1 [0.036]
1 1 0 [0.096]
1 1 1 [0.144]
[0.13999999999999999, 0.13999999999999999, 0.21, 0.21, 0.024, 0.036, 0.096, 0.144]
1.0
True


In [39]:
m3 = BayesianNetwork()
m3.add_nodes_from(['x','y','z'])
m3.add_edge('x','y')
m3.add_edge('y','z')
m3.get_independencies()

(x ⟂ z | y)
(z ⟂ x | y)

In [ ]:
m4 = BayesianNetwork()
m4.add_nodes_from(['x','y','z'])
m4.add_edge('z','y')
m4.add_edge('y','x')
m4.get_independencies()

In [ ]:
m5 = BayesianNetwork()
m5.add_nodes_from(['x','y','z'])
m5.add_edge('y','x')
m5.add_edge('y','z')
m5.add_edge('x','z')
m5.get_independencies()

In [ ]:
m6 = BayesianNetwork()
m6.add_nodes_from(['x','y','z'])
m6.add_edge('x','y')
m6.add_edge('y','z')
m6.add_edge('x','z')
m6.get_independencies()

In [ ]:
m7 = BayesianNetwork()
m7.add_nodes_from(['x','y','z'])
m7.add_edge('y','x')
m7.add_edge('z','y')
m7.add_edge('z','x')
m7.get_independencies()

In [ ]:
m8 = BayesianNetwork()
m8.add_nodes_from(['x','y','z'])
m8.add_edge('y','x')
m8.add_edge('y','z')
m8.add_edge('z','x')
m8.get_independencies()

In [ ]:
m9 = BayesianNetwork()
m9.add_nodes_from(['x','y','z'])
m9.add_edge('x','y')
m9.add_edge('z','y')
m9.add_edge('x','z')
m9.get_independencies()

In [ ]:
m10 = BayesianNetwork()
m10.add_nodes_from(['x','y','z'])
m10.add_edge('x','y')
m10.add_edge('z','y')
m10.add_edge('x','z')
m10.get_independencies()

In [ ]:
import pygraphviz as pgv
def dagviz(nodes, edges, name):
    G = pgv.AGraph(strict=False, directed=True)
    G.add_nodes_from(nodes)
    for edge in edges:
        G.add_edge(edge)
    G.write(name + ".dot")
    # use dot
    G.layout(prog="dot")
    # write previously positioned graph to PNG file
    G.draw(name + ".png")

In [ ]:
def viz_model(model, filename):
    dagviz(model.nodes, model.edges, filename)

In [ ]:
i = 1
for model in [m1,m2,m3,m4,m5,m6,m7,m8,m9,m10]:
    viz_model(model, "m" + str(i))
    i = i+1

In [83]:
import numpy as np
px = np.array([[0.4], [0.6]])
py = np.array([[0.7], [0.3]])
pz = np.array([[0.1], [0.9]])
pxy = np.multiply(px, py.transpose())
pxyz = np.multiply(pz, pxy.flatten())
print(pxyz.transpose().flatten())


[0.028 0.252 0.012 0.108 0.042 0.378 0.018 0.162]


In [82]:
pxyz.transpose().flatten().transpose()

array([0.028, 0.252, 0.012, 0.108, 0.042, 0.378, 0.018, 0.162])

In [67]:
p1 = [0.4, 0.6]
p2 = [0.7, 0.3]
p3 = [0.1, 0.9]
jpd = []
for i in p1:
    for j in p2:
        for k in p3:
            jpd.append(i * j * k)
print(jpd)

[0.027999999999999997, 0.252, 0.012, 0.108, 0.042, 0.378, 0.018, 0.162]


In [80]:
def create_bn(nodes, edges):
    model = BayesianNetwork()
    model.add_nodes_from(nodes)
    model.add_edges_from(edges)
    return model
    
def imap_demo1():
    m1 = create_bn(["X", "Y", "Z"], [])
    px = [[0.4], [0.6]]
    py = [[0.7], [0.3]]
    pz = [[0.1], [0.9]]
    cpd_X = TabularCPD(variable="X", variable_card=2, values=px)
    cpd_Y = TabularCPD(variable="Y", variable_card=2, values=py)
    cpd_Z = TabularCPD(variable="Z", variable_card=2, values=pz)
    print(cpd_Z.is_valid_cpd(), cpd_Y.is_valid_cpd(), cpd_X.is_valid_cpd())
    m1.add_cpds(cpd_X, cpd_Y, cpd_Z)
  
    pxy = np.multiply(px, py.transpose())
    pxyz = np.multiply(pz, pxy.flatten())
    print(pxyz)
    jpd = pxyz.transpose().flatten()
    print(jpd)
    JPD = JointProbabilityDistribution(["X", "Y", "Z"], [2, 2, 2], pxyz)
    check_imap = m1.is_imap(JPD)
    print(f"Bayesian network m1 has \n nodes: {m1.nodes} edges: {m1.edges} ")
    print(
        f"the model represents the following joint probability distribution on {m1.nodes}"
    )

    print(f"Conditional independencies are:")
    print(m1.get_independencies())
    print(f"Is m1 an I-map of the joint distribution?\nAnswer: {check_imap}")


In [81]:
imap_demo1()

True True True


AttributeError: 'list' object has no attribute 'transpose'

In [86]:
px = np.array([[0.4], [0.6]])
py = np.array([[0.7], [0.3]])
pz = np.array([[0.1], [0.9]])
jpd = (np.multiply(pz, (np.multiply(px, py.transpose())).flatten())).transpose().flatten()
print(jpd)

[0.028 0.252 0.012 0.108 0.042 0.378 0.018 0.162]


In [95]:
def bn2(p_y, p_x_y, p_z_y):
    m2 = BayesianNetwork()
    m2.add_nodes_from(["X", "Y", "Z"])
    m2.add_edge("Y", "X")
    m2.add_edge("Y", "Z")
    cpd_Y = TabularCPD(variable="Y", variable_card=2, values=  p_y)    
    cpd_X = TabularCPD(
        variable="X",
        variable_card=2,
        values=p_x_y,
        evidence=["Y"],
        evidence_card=[2],
    )
    cpd_Z = TabularCPD(
        variable="Z",
        variable_card=2,
        values=p_z_y,
        evidence=["Y"],
        evidence_card=[2],
    )
    # print(cpd_X.is_valid_cpd(), cpd_Y.is_valid_cpd(), cpd_Z.is_valid_cpd())
    m2.add_cpds(cpd_X, cpd_Y, cpd_Z)
    return m2

In [96]:
def imap_demo2():
    P_Y = np.array([[0.7], [0.3]])
    P_X_Y = np.array(
        [
            [0.4, 0.2],
            [0.6, 0.8],
        ]
    )
    P_Z_Y = np.array(
        [
            [0.5, 0.4],
            [0.5, 0.6],
        ]
    )
    m2 = bn2(P_Y, P_X_Y, P_Z_Y)
    jpd = []
    for Y in [0, 1]:
        for X in [0, 1]:
            for Z in [0, 1]:
                p_yxz = np.multiply(np.multiply(P_Y[Y], P_X_Y[X, Y]), P_Z_Y[Z, Y])
                print(p_yxz)
                jpd.append(p_yxz[0])
                print(Y, X, Z, p_yxz)
    print(jpd)
    print(sum(jpd))
    prob = JointProbabilityDistribution(["Y", "X", "Z"], [2, 2, 2], jpd)
    check_imap = m2.is_imap(prob)
    print(f"Bayesian network m1 has \n nodes: {m2.nodes} edges: {m2.edges} ")
    print(
        f"the model represents the following joint probability distribution on {m2.nodes}"
    )
    print(jpd)
    print(f"Conditional independencies are:")
    print(m2.get_independencies())
    print(f"Is m2 an I-map of the joint distribution?\nAnswer: {check_imap}")

In [97]:
imap_demo2()

[0.14]
0 0 0 [0.14]
[0.14]
0 0 1 [0.14]
[0.21]
0 1 0 [0.21]
[0.21]
0 1 1 [0.21]
[0.024]
1 0 0 [0.024]
[0.036]
1 0 1 [0.036]
[0.096]
1 1 0 [0.096]
[0.144]
1 1 1 [0.144]
[0.13999999999999999, 0.13999999999999999, 0.21, 0.21, 0.024, 0.036, 0.096, 0.144]
1.0
Bayesian network m1 has 
 nodes: ['X', 'Y', 'Z'] edges: [('Y', 'X'), ('Y', 'Z')] 
the model represents the following joint probability distribution on ['X', 'Y', 'Z']
[0.13999999999999999, 0.13999999999999999, 0.21, 0.21, 0.024, 0.036, 0.096, 0.144]
Conditional independencies are:
(Z ⟂ X | Y)
(X ⟂ Z | Y)
Is m2 an I-map of the joint distribution?
Answer: True


In [98]:
jpd = []
for Y in [0, 1]:
    for X in [0, 1]:
        for Z in [0, 1]:
            p_yxz = np.multiply(np.multiply(P_Y[Y], P_X_Y[X, Y]), P_Z_Y[Z, Y])
            jpd.append(p_yxz[0])
print(jpd)

[0.13999999999999999, 0.13999999999999999, 0.21, 0.21, 0.024, 0.036, 0.096, 0.144]


In [101]:
px = np.array([[0.4], [0.6]])
py = np.array([[0.7], [0.3]])
pz = np.array([[0.1], [0.9]])
jpd = (np.multiply(pz, (np.multiply(px, py.transpose())).flatten())).transpose().flatten()
print(jpd)

[0.028 0.252 0.012 0.108 0.042 0.378 0.018 0.162]


In [108]:
P_Y = np.array([[0.7], [0.3]])
P_X_Y = np.array(
        [
            [0.4, 0.2],
            [0.6, 0.8],
        ]
    )
P_Z_Y = np.array(
        [
            [0.5, 0.4],
            [0.5, 0.6],
        ]
    )
pxy = P_X_Y.flatten()
pzy = P_Z_Y.flatten().reshape(4,1)
print(np.multiply(pxy, pzy))

[[0.2  0.1  0.3  0.4 ]
 [0.16 0.08 0.24 0.32]
 [0.2  0.1  0.3  0.4 ]
 [0.24 0.12 0.36 0.48]]


In [115]:
from math import comb
print(comb(3,2))


3


In [117]:
def create_bn(nodes, edges):
    model = BayesianNetwork()
    model.add_nodes_from(nodes)
    model.add_edges_from(edges)
    return model

In [118]:
m = create_bn(['A','B','C','D'],[('A','B'),('A','C'),('B','D'),('C','D')])

In [119]:
m.get_independencies()

(B ⟂ C | A)
(D ⟂ A | B, C)
(C ⟂ B | A)
(A ⟂ D | B, C)

In [121]:
m = create_bn(['A','S','T','L','E','B','X','D'],
              [('A','T'),('S','L'),('S','B'),('T','E'),('L','E'),('E','X'),('E','D'),('B','D')])

In [123]:
from util import d_sep
d_sep(m,['B'],['S'],['T'])

no edge: (B, S) 


True

In [124]:
d_sep(m,['B'],['S','T'],['A','L','E','X'])

no edge: (B, S) 
no edge: (B, T) 


True

In [125]:
d_sep(m,['B'],['S'],['T','A','L','E','X'])

no edge: (B, S) 


True

In [134]:
from util import d_sep, viz_model
def demo_graphoid_intersection():
    nodes = ["A", "S", "T", "L", "E", "B", "X", "D"]
    edges = [
        ("A", "T"),
        ("S", "L"),
        ("S", "B"),
        ("T", "E"),
        ("L", "E"),
        ("E", "X"),
        ("E", "D"),
        ("B", "D"),
    ]
    m = create_bn(nodes, edges)
    print(f"created Bayesian network model")
    name = "graphoid_demo"
    viz_model(m, name)
    print(f"Nodes:\n{nodes}\nEdges\n{edges}")
    X = ["E"]
    Y = ["A"]
    W = ["S"]
    Z = ["T", "D", "B", "X","L"]
    print(f"created graph layout inf files: {name}.dot and {name}.png")
    res1 = d_sep(m, ["E"], ["A"], ["T", "D", "B", "X","L","S"])
    print(f"I({X}, {Z} U {W}, {Y}) is {res1}")
    #%%
    res2 = d_sep(m, ["E"], ["S"], ["T", "D", "B", "X","L","A"])
    print(f"I({X}, {Z} U {Y}, {W}) is {res2}")
    #%%
    res3 = d_sep(m, ["E"], ["S","A"], ["T", "D", "B", "X","L"])
    print(f"I({X}, {Z}, {W} U {Y}) is {res3}")
    print(f"verified intersection axiom")

In [135]:
demo_graphoid_intersection()

created Bayesian network model
Nodes:
['A', 'S', 'T', 'L', 'E', 'B', 'X', 'D']
Edges
[('A', 'T'), ('S', 'L'), ('S', 'B'), ('T', 'E'), ('L', 'E'), ('E', 'X'), ('E', 'D'), ('B', 'D')]
created graph layout inf files: graphoid_demo.dot and graphoid_demo.png
no edge: (E, A) 
I(['E'], ['T', 'D', 'B', 'X', 'L'] U ['S'], ['A']) is True
no edge: (E, S) 
I(['E'], ['T', 'D', 'B', 'X', 'L'] U ['A'], ['S']) is True
no edge: (E, S) 
no edge: (E, A) 
I(['E'], ['T', 'D', 'B', 'X', 'L'], ['S'] U ['A']) is True
verified intersection axiom


In [133]:
d_sep(m, ["E"], ["A"], ["T", "D", "B", "X","L","S"])

no edge: (E, A) 


True

In [131]:
def demo_graphoid_contraction():
    nodes = ["A", "S", "T", "L", "E", "B", "X", "D"]
    edges = [
        ("A", "T"),
        ("S", "L"),
        ("S", "B"),
        ("T", "E"),
        ("L", "E"),
        ("E", "X"),
        ("E", "D"),
        ("B", "D"),
    ]
    m = create_bn(nodes, edges)
    print(f"created Bayesian network model")
    name = "graphoid_demo"
    viz_model(m, name)
    print(f"Nodes:\n{nodes}\nEdges\n{edges}")
    X = ["B"]
    Y = ["T"]
    Z = ["S"]
    W = ["A", "L", "E", "X"]
    print(f"created graph layout inf files: {name}.dot and {name}.png")
    res1 = d_sep(m, ["B"], ["S"], ["T"])
    print(f"I({X}, {Z}, {Y}) is {res1}")
    #%%
    res2 = d_sep(m, ["B"], ["S", "T"], ["A", "L", "E", "X"])
    print(f"I({X}, {Z} U {Y}, {W}) is {res2}")
    #%%
    res3 = d_sep(m, ["B"], ["S"], ["T", "A", "L", "E", "X"])
    print(f"I({X}, {Z}, {W} U {Y}) is {res3}")
    print(f"verified contraction axiom")

In [132]:
demo_graphoid_contraction()

created Bayesian network model
Nodes:
['A', 'S', 'T', 'L', 'E', 'B', 'X', 'D']
Edges
[('A', 'T'), ('S', 'L'), ('S', 'B'), ('T', 'E'), ('L', 'E'), ('E', 'X'), ('E', 'D'), ('B', 'D')]
created graph layout inf files: graphoid_demo.dot and graphoid_demo.png
no edge: (B, S) 
I(['B'], ['S'], ['T']) is True
no edge: (B, S) 
no edge: (B, T) 
I(['B'], ['S'] U ['T'], ['A', 'L', 'E', 'X']) is True
no edge: (B, S) 
I(['B'], ['S'], ['A', 'L', 'E', 'X'] U ['T']) is True
verified contraction axiom


In [154]:
nodes = {'A', 'S', 'T', 'L', 'E', 'B', 'X', 'D'}
node = 'L'
nodes.remove(node)
print(nodes)
blanket = {'S', 'E', 'T'}

print(nodes.difference(blanket))


{'D', 'A', 'E', 'S', 'B', 'X', 'T'}
{'B', 'D', 'X', 'A'}


In [155]:
nodes = ['A', 'S', 'T', 'L', 'E', 'B', 'X', 'D']
node = 'L'
nodes.remove(node)
print(nodes)
blanket = ['S', 'E', 'T']
print(nodes.difference(blanket))

['A', 'S', 'T', 'E', 'B', 'X', 'D']


AttributeError: 'list' object has no attribute 'difference'